### PR TITLE
[followup #23] Add xc compat, improve Travis and regen oasis

### PR DESCRIPTION
**Pull request by avsm**
followup #23

### CODE REVIEW

**Comment by avsm** [comment]
```
#=== ERROR while installing xen-gnt.2.2.1 =====================================#
# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
# os                   linux
# command              make
# path                 /home/opam/.opam/4.03.0/build/xen-gnt.2.2.1
# compiler             4.03.0
# exit-code            2
# env-file             /home/opam/.opam/4.03.0/build/xen-gnt.2.2.1/xen-gnt-5124-7fbc68.env
# stdout-file          /home/opam/.opam/4.03.0/build/xen-gnt.2.2.1/xen-gnt-5124-7fbc68.out
# stderr-file          /home/opam/.opam/4.03.0/build/xen-gnt.2.2.1/xen-gnt-5124-7fbc68.err
### stdout ###
# lib/gnttab_stubs.c:130:28: note: in expansion of macro '_G'
# [...]
# Command exited with code 2.
```

**Comment by mato** [comment]
@avsm This fails because `xen-gnt` had a similar change added in mirage/ocaml-gnt@241ca2e however this is not in `2.2.1` released to OPAM (mirage/ocaml-gnt@7ecf3cd). Both of these packages (i.e. `xen-gnt` master and `xen-evtchn` _with_ 8b4a367) need to be added to `mirage-dev`.

**Comment by mato** [comment]
(...) _or_ we could just cut new point releases of `xen-gnt` and `xen-evtchn` and push them to OPAM without going through mirage-dev -- AFAICT there aren't any backward incompatible changes in there. /cc @djs55

**Comment by djs55** [comment]
@mato I'll look at releasing `xen-evtchn` today.

**Comment by mato** [comment]
@djs55 Thanks. `xen-gnt` also needs a release as the current one is missing mirage/ocaml-gnt@241ca2e.

**Comment by djs55** [comment]
Oh sorry a typo: I meant I would look at `xen-gnt` first :) I'll look at `xen-evtchn` after that!

**Comment by djs55** [comment]
ah, they might need to be released together as the CI runs depend on each other

**Pull request merged**
